apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APPNAME}
  namespace: 51hone
  labels:
    app: {APPNAME}
spec:
  selector:
    matchLabels:
      app: {APPNAME}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {APPNAME}
    spec:
      containers:
        - name: application
          image: "{APP_IMAGE}"
          ports:
            - containerPort: 80
          env:
            - name: PROXY_HONE_SERVER
              value: gateway:8080/
